version: "2.4"

x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: always
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true
    
volumes: 
  rancher_data:

services:
  rancher:
    <<: *default
    image: rancher/rancher:v2.5-head
    volumes:
      - rancher_data:/var/lib/rancher
    # ports:
    #   - 80:80
    #   - 443:443
    hostname: rancher
    container_name: rancher
    restart: always
    # command: --acme-domain <YOUR.DNS.NAME>
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.api.rule=Host(`rancher.example.com`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls.certresolver=ssl"
      - "traefik.http.services.api.loadbalancer.server.port=80"
