x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

volumes:
  n8n_data:

networks:
  traefik-net:
    external: true

services:
  n8n:
    <<: *default
    image: docker.n8n.io/n8nio/n8n
    # ports:
    #   - "127.0.0.1:5678:5678"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.n8n.rule=Host(`n8n.example.com`)"
      - "traefik.http.routers.n8n.entrypoints=https"
      - "traefik.http.routers.n8n.tls.certresolver=ssl"
      - "traefik.http.routers.n8n.middlewares=dev-auth"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
    environment:
      - N8N_HOST=n8n.example.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.example.com/
      # - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n

