version: '3.1'

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    environment:
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: root
      SONARQUBE_JDBC_URL: jdbc:mysql://mysql:3306/sonar_source?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    hostname: sonarqube
    networks:
        - db-back

  mysql:
    image: mysql:5.7
    networks:
      - db-back
    volumes:
      - ./mysql-data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sonar_source
    ports:
      - "0.0.0.0:3309:3306"
    hostname: mysql
    # restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"