# Create password: docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'YOUR_PASSWORD'


x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true

services:
  wireguard:
    <<: *default
    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wireguard
    hostname: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      LANG: en
      WG_HOST: "<YOUR_SERVER_IP>"
      PASSWORD_HASH: "$$2a$$12$$GRWi.SNYpZovU/cLZOpz8.7AVPS2GJz49/6GrpVkjUuRad3ytbG6W" # admin
      PORT: 8080 # UI port
      WG_PORT: 51820
      WG_DEFAULT_ADDRESS: 10.8.0.x # Clients IP address range.

    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "8080:8080/tcp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
