# See settings from: https://devopscube.com/setup-and-configure-proxy-server/
# --------------------------------------------------------------------------------

version: "2.4"

x-default: &default
  networks:
    - squid-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: always
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  squid-net:
    # external: true
    
volumes: 
  squid_data:
  
services:
  squid:
    <<: *default
    image: sameersbn/squid:3.5.27-2
    container_name: squid
    hostname: squid
    ports:
      - 4000:3128
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.api.rule=Host(`example.com`)"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls.certresolver=ssl"
      - "traefik.http.services.api.loadbalancer.server.port=3128"

    volumes:
      - squid_data:/var/spool/squid
      - ./squid-conf/squid.conf:/etc/squid/squid.conf
      - ./squid-conf/auth:/etc/squid/auth

