

x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true
  
services:
  skyhook:
    <<: *default
    image: cuongnb14/skyhook:1.0
    container_name: skyhook
    hostname: skyhook
    # ports:
    #   - 127.0.0.1:8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.skyhook.rule=Host(`skyhook.example.com`)"
      - "traefik.http.routers.skyhook.entrypoints=https"
      - "traefik.http.routers.skyhook.tls.certresolver=ssl"
      - "traefik.http.services.skyhook.loadbalancer.server.port=8080"

