x-default:
  &default
  networks:
    - runner-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  runner-net:

services:

  gitlab_runner:
    <<: *default
    image: gitlab/gitlab-runner:1.0
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: gitlab_runner
    hostname: gitlab_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
      - ./scripts:/home/gitlab-runner/scripts
      - ./ssh:/home/gitlab-runner/.ssh
