

services:
  swarm_visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:8080
    hostname: swarm_visualizer
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"
