

x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true

volumes:
  wordpress_data:
  mysql_data:
  
services:

  wordpress:
    <<: *default
    image: wordpress:php7.4-apache
    container_name: wordpress
    hostname: wordpress
    # ports:
    #   - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./php-conf/.htaccess:/var/www/html/.htaccess
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.com`)"
      - "traefik.http.routers.wordpress.entrypoints=https"
      - "traefik.http.routers.wordpress.tls.certresolver=ssl"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  db:
    <<: *default
    image: mysql:5.7
    container_name: wordpress_db
    hostname: wordpress_db
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql_data:/var/lib/mysql
