version: '2.4'

x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: always
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true
    
services:

  wordpress:
    <<: *default
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # - ./wordpress:/var/www/html
      - ./php-conf/.htaccess:/var/www/html/.htaccess
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.webhook.rule=Host(`wordpress.com`)"
      - "traefik.http.routers.webhook.entrypoints=https"
      - "traefik.http.routers.webhook.tls.certresolver=ssl"
      - "traefik.http.services.webhook.loadbalancer.server.port=80"

  db:
    <<: *default
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
