version: '2.4'

x-default: &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: always
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true

volumes:
  postgres_data:
  
services:
  pghero:
    <<: *default
    image: ankane/pghero:v2.8.1
    container_name: pghero
    hostname: pghero
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DATABASE_URL: postgres://user:pass@host:port/dbname
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.pghero.rule=Host(`pghero.example.com`)"
      - "traefik.http.routers.pghero.entrypoints=https"
      - "traefik.http.routers.pghero.tls.certresolver=ssl"
      - "traefik.http.routers.pghero.middlewares=dev-auth"
      - "traefik.http.services.pghero.loadbalancer.server.port=8080"
