# https://github.com/jenkinsci/docker/blob/master/README.md


services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    hostname: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
