

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - zoo-back

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "comment_notify:1:1,feed_published:1:1,feed_unpublished:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: kafka
    restart: unless-stopped
    networks:
      - zoo-back
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

networks:
    zoo-back:
