x-environment:
  &default-environment
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  SECRET_KEY: change-me
  PORT: 8000
  EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
  GLITCHTIP_DOMAIN: https://glitchtip.example.com # Change this to your domain
  DEFAULT_FROM_EMAIL: email@glitchtip.com # Change this to your email
  CELERY_WORKER_AUTOSCALE: "1,3"  # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"
  ENABLE_USER_REGISTRATION: false
  ENABLE_ORGANIZATION_CREATION: false

x-depends_on:
  &default-depends_on
  - postgres
  - redis

x-default:
  &default
  networks:
    - traefik-net
  # cpus: 0.5
  # mem_limit: 500M
  restart: unless-stopped
  # init: true
  # privileged: true
  # stdin_open: true
  # tty: true
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

networks:
  traefik-net:
    external: true

services:
  postgres:
    <<: *default
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"  # Consider removing this and setting a password
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    <<: *default
    image: redis
  web:
    <<: *default
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    ports:
      - "127.0.0.1:8000:8000"
    environment: *default-environment
    volumes: 
      - uploads:/code/uploads
    
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik-net
      traefik.http.routers.glitchtip.rule: Host(`glitchtip.example.com`)
      traefik.http.routers.glitchtip.entrypoints: https
      traefik.http.routers.glitchtip.tls.certresolver: ssl
      traefik.http.services.glitchtip.loadbalancer.server.port: 8000
  
  worker:
    <<: *default
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    volumes: 
      - uploads:/code/uploads
  migrate:
    <<: *default
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    command: "./manage.py migrate"
    environment: *default-environment

volumes:
  pg-data:
  uploads:
