

services:
  mongo:
    image: mongo
    networks:
      - db-back
    volumes:
      - ./mongo-data/:/data/db
    ports:
      - "27017:27017"
    hostname: mongo
    # restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

networks:
  db-back:
    #external: true
