version: "3"

services:
  redis:
    image: redis:3.2
    volumes:
      - ./cassandra-data/:/var/lib/cassandra
    ports:
      - 6379:6379
    hostname: redis
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

